### ISSUE TITLE
Tests do not appear to be run

### ISSUE THREAD

**Issue by mernst** [typetools/templatefora-checker#8]
Running `./gradlew build` succeeds.

If I remove the line
```
        // :: error: assignment.type.incompatible
```
from file `tests/templatefora/SubtypingTest.java`, `./gradlew build` still succeeds.  This suggests that the files in `tests/templatefora/` are not being type-checked as they should be.

Actually, if I introduce a syntax error into file `SubtypingTest.java`, the build still succeeds!  So maybe the tests are being ignored altogether?

Please make the buildfile type-check test files.

**Comment by kelloggm** [comment]
I cannot reproduce the problem as described: if I checkout a fresh copy of this repository, make a change to `tests/templatefora/SubtypingTest.java` as you describe, and run `.gradlew build`, the tests fail.

However, I *can* reproduce the problem if I run `./gradlew build` once on the clean copy of the repository, then make the offending change, and then run `./gradlew build` again.

My conclusion is that the test files are not being declared as inputs to Gradle, so it believes it need not rerun them. I'm opening a PR to fix that.

**Comment by mernst** [comment]
Thanks for diagnosing the problem.
